基于Django导航系统/Navigation_ system/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^design/',include('design.urls',namespace='design'))
]

基于Django导航系统/design/urls.py
from django.conf.urls import url

from design import views

urlpatterns = [
    url(r'^login/',views.login,name='login'),
    url(r'^register/',views.register,name='register'),
    url(r'^index/',views.index,name='index'),
    url(r'^search/',views.search,name='search'),
    url(r'^drawing/',views.drawing,name='drawing'),
    url(r'^clickImg/',views.clickImg,name='clickImg'),
    url(r'^user_base_info/',views.user_base_info,name='user_base_info'),
    url(r'^user_pic_info/',views.user_pic_info,name='user_pic_info'),
    url(r'^user_pass_info/',views.user_pass_info,name='user_pass_info'),
    url(r'^user_collection/',views.user_collection,name='user_collection'),
    url(r'^logout/',views.logout,name='logout'),
    url(r'^collection/',views.collection,name='colletcion'),
]

基于Django导航系统/templates/user/user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>用户中心</title>
    <link rel="stylesheet" type="text/css" href="/static/css/reset.css">
    <link rel="stylesheet" type="text/css" href="/static/css/main.css">
    <script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
    <script type="text/javascript" src="/static/js/main.js"></script>
</head>

<body>
<div class="header_con">
    <div class="header">
        <a href="{% url 'design:index' %}" class="logo fl">
            <img src="/static/imgs/logo.jpg" alt="logo" style="height: 50px;width: 50px">
        </a>
        {% if token %}
            <div class="user_login fr" style="display: block;">
                <img src="{{ icon }}" class="lgin_pic">
                <a>{{ user.username }}</a>
                <a href="{% url 'design:logout' %}">退出</a>
            </div>
        {% else %}
            <div class="user_btns fr">
                <a href="{% url 'design:login' %}" class="login_btn">登录</a>
                <a href="{% url 'design:register' %}" class="register_btn">注册</a>
            </div>
        {% endif %}
    </div>
</div>
<div class="conter_con">
    <div class="user_menu_con fl">
        {% if token %}
            <div class="user_center_pic">
                <img src="{{ icon }}">
            </div>
        {% endif %}
        <div class="user_center_name">{{ user.username }}</div>
        <ul class="option_list">
            <li class="active"><a href="{% url 'design:user_base_info' %}" target="main_frame">基本资料</a></li>
            <li><a href="{% url 'design:user_pic_info' %}" target="main_frame">头像设置</a></li>
            <li><a href="{% url 'design:user_pass_info' %}" target="main_frame">密码修改</a></li>
            <li><a href="{% url 'design:user_collection' %}" target="main_frame">我的收藏</a></li>
        </ul>
    </div>
    <div class="user_con fr">
        <iframe src="{% url 'design:user_base_info' %}" frameborder="0" name="main_frame" class="main_frame"
                id="main_frame"></iframe>
    </div>
</div>
<div class="footer">
    <div class="footer_links">
        <a href="">关于我们</a>
        <span>|</span>
        <a href="">联系我们</a>
        <span>|</span>
        <a href="">招聘人才</a>
        <span>|</span>
        <a href="">友情链接</a>
    </div>
</div>
</body>
</html>

基于Django导航系统/templates/user/user_base_info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>用户中心</title>
    <link rel="stylesheet" type="text/css" href="/static/css/reset.css">
    <link rel="stylesheet" type="text/css" href="/static/css/main.css">
    <script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
</head>
<body class="inframe_body">
{% if phone %}
    <form class="base_info" method="post" action="{% url 'design:user_base_info' %}">
    {% csrf_token %}
        <h3>基本资料</h3>
        <div class="form-group">
            <label>用户名：</label>
            <input id="username" type="text" name="username" class="input_txt" value="{{ username }}">
        </div>
        <div class="form-group">
            <label>手机号：</label>
            <input id="phone" type="text" name="phone" class="input_txt" value="{{ phone }}">
        </div>
        <div class="form-group">
            <label>用户昵称：</label>
            <input id="nick_name" type="text" name="nick_name" class="input_txt" value="{{ nickname }}">
        </div>
        <div class="form-group">
            <label>性别：</label>
            <input class="gender" type="radio" name="gender" value="MAN"
                    {% if sex == True  %}
                   checked="checked"
                    {% endif %}
            > <b>男</b>&nbsp;&nbsp;&nbsp;&nbsp;
            <input class="gender" type="radio" name="gender" value="WOMAN"
                    {% if sex == False %}
                   checked="checked"
                    {% endif %}
            > <b>女</b>
        </div>
        <div class="form-group">

            <input type="submit" value="保 存" class="input_sub">

        </div>
    </form>
{% else %}
    <h3>基本资料</h3>
    <div class="form-group">
        <label>用户名：</label>
        <input id="username" type="text" name="username" class="input_txt" disabled>
    </div>
    <div class="form-group">
        <label>手机号：</label>
        <input id="phone" type="text" name="phone" class="input_txt" disabled>
    </div>
    <div class="form-group">
        <label>用户昵称：</label>
        <input id="nick_name" type="text" name="nick_name" class="input_txt" disabled>
    </div>
    <div class="form-group">
        <label>性别：</label>
        <input class="gender" type="radio" name="gender" value="MAN"
                {% if sex == True  %}
               checked="checked"
                {% endif %}
        disabled> <b>男</b>&nbsp;&nbsp;&nbsp;&nbsp;
        <input class="gender" type="radio" name="gender" value="WOMAN"
                {% if sex == False %}
               checked="checked"
                {% endif %}
        disabled> <b>女</b>
    </div>
{% endif %}

</body>
</html>

基于Django导航系统/templates/user/user_collection.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>用户中心</title>
    <link rel="stylesheet" type="text/css" href="/static/css/reset.css">
    <link rel="stylesheet" type="text/css" href="/static/css/jquery.pagination.css">
    <link rel="stylesheet" type="text/css" href="/static/css/main.css">
    <link rel="stylesheet" href="/static/css/button.css">
    <script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
    <script type="text/javascript" src="/static/js/jquery.pagination.min.js"></script>
</head>
<body class="inframe_body">
<div class="my_collect">
    <h3>我的收藏</h3>
    {% if token %}
        <form id="t">
            <div id="line">
                收 藏 路 线
            </div>
            <table id="table" align="center">
                {% for col in collection %}
                    <tr>
                        <td>
                            <div id="text">
                                起点：<input name="start" value="{{ col.line_origin }}" disabled/>
                                终点：<input name="end" value="{{ col.line_destination }}" disabled/>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </form>
        <form id="t">
            <div id="line">
                收 藏 地 点
            </div>
            <table id="table" align="center">
                {% for site in sites %}
                    <tr>
                        <td>
                            <div id="text">
                                <input value="{{ site.site }}" disabled>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </form>
    {% else %}
        <div id="line">
            收 藏 路 线
        </div>
        <form id="t">
            <div id="line">
                收 藏 地 点
            </div>
        </form>
    {% endif %}
</div>
</body>
</html>

基于Django导航系统/templates/user/user_pass_info.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>用户中心</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
    <script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
</head>
<body class="inframe_body">
    <form class="pass_info" method="post" action="{% url 'design:user_pass_info' %}" onsubmit="return check(this)">
        {% csrf_token %}
        {% if token %}
            <h3>密码修改</h3>
            <div class="form-group">
                <label>当前密码：</label>
                <input type="password" name="old_password" class="input_txt">
            </div>
            <div class="form-group">
                <label>新密码：</label>
                <input type="password" name="new_password" class="input_txt">
            </div>
            <div class="form-group">
                <label>确认密码：</label>
                <input type="password" name="new_password2" class="input_txt">
            </div>
            <div class="error_tip">提示信息</div>
            <div class="form-group">
                <input type="submit" value="保 存" class="input_sub">
            </div>
        {% else %}
            <h3>密码修改</h3>
            <div class="form-group">
                <label>当前密码：</label>
                <input type="password" name="old_password" class="input_txt" disabled>
            </div>
            <div class="form-group">
                <label>新密码：</label>
                <input type="password" name="new_password" class="input_txt" disabled>
            </div>
            <div class="form-group">
                <label>确认密码：</label>
                <input type="password" name="new_password2" class="input_txt" disabled>
            </div>
            <div class="error_tip">提示信息</div>
            <div class="form-group">
                <input type="submit" value="保 存" class="input_sub" disabled>
            </div>
        {% endif %}
    </form>
    <script type="text/javascript">
        function check(form) {
            if (form.old_password.value == "" ){
                alert('原密码不能为空！');
                form.old_password.focus();
                return false
            }
            if (form.new_password.value == "" ){
                alert('新密码不能为空！');
                form.new_password.focus();
                return false
            }
            if (form.new_password2.value == "" ){
                alert('确认密码不能为空！');
                form.old_password.focus();
                return false
            }
            if (form.new_password.value != form.new_password2.value ){
                alert('两次密码不一致！');
                form.old_password.focus();
                return false
            }
            return true
        }
    </script>
</body>
</html>

基于Django导航系统/templates/user/user_pic_info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>用户中心</title>
    <link rel="stylesheet" type="text/css" href="/static/css/reset.css">
    <link rel="stylesheet" type="text/css" href="/static/css/main.css">
    <script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
    <script type="text/javascript" src="/static/js/jquery.form.min.js"></script>
</head>
<body class="inframe_body">

<h3>头像设置</h3>
{% if url %}
    <div class="form-group">
        <label class="label01">当前图像：</label>
        <img src="{{ url }}" alt="用户图片" class="now_user_pic">
    </div>
    <div class="form-group">
        <label>上传图像：</label>
        <form method="post" html="{:multipart=>true}" data-remote="true"
              action="{% url 'design:user_pic_info' %}" accept-charset="UTF-8"
              enctype="multipart/form-data">
            {% csrf_token %}
            <input type="file" name="icon" value="头像" placeholder="点击更换头像">
            <br>
            <input id="button" class="input_sub" type="submit" value="保存">
        </form>
    </div>
{% else %}
    <div class="form-group">
        <label>上传图像：</label>
        <input type="file" name="pic" value="头像" disabled>
    </div>
    <div class="form-group">
        <input type="submit" value="保 存" class="input_sub" disabled>
    </div>
{% endif %}
</body>
</html>