基于Django导航系统/Navigation_ system/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^design/',include('design.urls',namespace='design'))
]

基于Django导航系统/design/urls.py
from django.conf.urls import url

from design import views

urlpatterns = [
    url(r'^login/',views.login,name='login'),
    url(r'^register/',views.register,name='register'),
    url(r'^index/',views.index,name='index'),
    url(r'^search/',views.search,name='search'),
    url(r'^drawing/',views.drawing,name='drawing'),
    url(r'^clickImg/',views.clickImg,name='clickImg'),
    url(r'^user_base_info/',views.user_base_info,name='user_base_info'),
    url(r'^user_pic_info/',views.user_pic_info,name='user_pic_info'),
    url(r'^user_pass_info/',views.user_pass_info,name='user_pass_info'),
    url(r'^user_collection/',views.user_collection,name='user_collection'),
    url(r'^logout/',views.logout,name='logout'),
    url(r'^collection/',views.collection,name='colletcion'),
]

基于Django导航系统/templates/drawing-route.html
<!doctype html>
<html>

	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="initial-scale=1.0, user-scalable=no, width=device-width">
		<title>城市公交线路查询</title>
		<style type="text/css">
			html,
			body,
			#container {
				width: 100%;
				height: 100%;
			}
		</style>
		<style type="text/css">
			#panel {
				position: fixed;
				background-color: white;
				max-height: 90%;
				overflow-y: auto;
				top: 10px;
				right: 10px;
				width: 280px;
			}

			#panel .amap-call {
				background-color: #009cf9;
				border-top-left-radius: 4px;
				border-top-right-radius: 4px;
			}
			
			#panel .amap-lib-transfer {
				border-bottom-left-radius: 4px;
				border-bottom-right-radius: 4px;
				overflow: hidden;
			}
		</style>
		<link rel="stylesheet" href="/static/css/demo-center.css" />
		<script src="/static/js/demoutils.js"></script>
		<script type="text/javascript" src="https://webapi.amap.com/maps?v=1.4.13&key=b88893a5bf189350d47e335b55ad8794&plugin=AMap.Transfer"></script>
		<script type="text/javascript" src="/static/js/addtoolbar.js"></script>
	</head>

	<body>
		<div id="container"></div>
		<div id="panel"></div>
		<script type="text/javascript">
			var map = new AMap.Map("container", {
				resizeEnable: true,
				center: [116.397428, 39.90923],
				zoom: 13
			});
			var transOptions = {
				map: map,
				city: '郑州',
				panel: 'panel',
				policy: AMap.TransferPolicy.LEAST_TIME //乘车策略
			};
			//构造公交换乘类
			var transfer = new AMap.Transfer(transOptions);
			//根据起、终点名称查询公交换乘路线
			transfer.search([{
					keyword: '{{ start }}',
					city: '郑州'
				},
				//第一个元素city缺省时取transOptions的city属性
				{
					keyword: '{{ end }}',//输入终点
					city: '郑州'
				}
				//第二个元素city缺省时取transOptions的cityd属性
			], function(status, result) {
				// result即是对应的公交路线数据信息，相关数据结构文档请参考  https://lbs.amap.com/api/javascript-api/reference/route-search#m_TransferResult
				if(status === 'complete') {
					log.success('绘制公交路线完成')
				} else {
					log.error('公交路线数据查询失败' + result)
				}
			});
		</script>
	</body>

</html>

基于Django导航系统/templates/index.html
{% load staticfiles %}
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no, width=device-width">
    <title>公交查询系统</title>
    <link rel="stylesheet" href="/static/css/lbs.css"/>
    <link rel="stylesheet" href="/static/css/site.css">
    <script type="text/javascript"
            src="https://webapi.amap.com/maps?v=1.4.14&key=b88893a5bf189350d47e335b55ad8794&plugin=AMap.Autocomplete,AMap.PlaceSearch"></script>
    <script type="text/javascript" src="/static/js/addtoolbar.js"></script>
</head>
<body>
<div id="container"></div>
<div id="myPageTop">
    <table id="tip">
            <input placeholder="搜索位置、公交站、地铁站" style="float: left" id="tipinput"/>
        <form action="{% url 'design:search' %}">
            {% csrf_token %}
            <br>&nbsp;
            <input class="button" type="submit" value="线路搜索" style="float: left">&nbsp;
            <a href="{% url 'design:search' %}">
                <img src="/static/imgs/路线.png" style="width: 20px;height: 26px">
            </a>
        </form>
    </table>
</div>
<div id="user">
    {% if users %}
        <a href="{% url 'design:clickImg' %}">
            <img src="{{ url }}" alt="登录头像">
        </a>
    {% else %}
        <a href="{% url 'design:clickImg' %}">
            <img src="/static/imgs/登录背景图.jpeg" alt="默认头像">
        </a>
    {% endif %}
</div>
<script type="text/javascript">
    //地图加载
    var map = new AMap.Map("container", {
        resizeEnable: true
    });
    //输入提示
    var autoOptions = {
        input: "tipinput"
    };
    var auto = new AMap.Autocomplete(autoOptions);
    var placeSearch = new AMap.PlaceSearch({
        map: map
    });  //构造地点查询类
    AMap.event.addListener(auto, "select", select);//注册监听，当选中某条记录时会触发
    function select(e) {
        placeSearch.setCity(e.poi.adcode);
        placeSearch.search(e.poi.name);  //关键字查询查询
    }
</script>
</body>
</html>

基于Django导航系统/templates/login-register.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>

    <style>
        body {
        padding-top: 60px;
        }
    </style>

    <link href="/static/bootstrap3/css/bootstrap.css" rel="stylesheet"/>

    <link href="/static/css/login-register.css" rel="stylesheet"/>
    <link rel="stylesheet" href="/static/css/font_awesome.css">

    <script src="/static/js/jquery-1.10.2.js" type="text/javascript"></script>
    <script src="/static/bootstrap3/js/bootstrap.js" type="text/javascript"></script>
    <script src="/static/js/login-register.js" type="text/javascript"></script>

</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-sm-4"></div>
        <div class="col-sm-4">
            <a class="btn big-login" data-toggle="modal" href="javascript:void(0)" onclick="openLoginModal();">登录</a>
            <a class="btn big-register" data-toggle="modal" href="javascript:void(0)"
               onclick="openRegisterModal();">注册</a></div>
        <div class="col-sm-4"></div>
    </div>


    <div class="modal fade login" id="loginModal">
        <div class="modal-dialog login animated">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">登录</h4>
                </div>
                <div class="modal-body">
                    <div class="box">
                        <div class="content">
                            <div class="error"></div>
                            <div class="form loginBox">
                                <form method="post" action="{% url 'design:login' %}" onsubmit="return login()" accept-charset="UTF-8">
                                    {% csrf_token %}
                                    <input id="phone1" class="form-control" type="text" placeholder="手机号" name="phone">
                                    <input id="password1" class="form-control" type="password" placeholder="密码"
                                           name="password">
                                    <input id="signsubmit" class="btn btn-default btn-login" type="submit" value="登录">
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="box">
                        <div class="content registerBox" style="display:none;">
                            <div class="form">
                                <form method="post" html="{:multipart=>true}" data-remote="true"
                                      action="{% url 'design:register' %}" accept-charset="UTF-8"
                                      onsubmit="return check(this)" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    <input type="file" name="icon" value="头像">
                                    <input id="username" class="form-control" type="text" placeholder="用户名"
                                           name="username">
                                    <input id="nickname" class="form-control" type="text" placeholder="昵称"
                                           name="nickname">
                                    <input id="phone" class="form-control" type="text" placeholder="手机号" name="phone">
                                    <div>
                                        <label for="sex">性别：</label>
                                        <select name="sex" id="sex">
                                            <option value="">男</option>
                                            <option value="">女</option>
                                        </select>
                                    </div>
                                    <input id="birthday" class="form-control" type="date"
                                           name="birthday">
                                    <input id="password" class="form-control" type="password" placeholder="密码"
                                           name="password">
                                    <input id="password_confirmation" class="form-control" type="password"
                                           placeholder="确认密码" name="password_confirmation">
                                    <input id="count" class="btn btn-default btn-register" type="submit" value="注册" name="commit">
                                    <a id="error" value="{{ count }}"></a>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <div class="forgot login-footer">
                            <span>马上去
                                 <a href="javascript: showRegisterForm();">创建账号</a>
                            ?</span>
                    </div>
                    <div class="forgot register-footer" style="display:none">
                        <span>已经有账号?</span>
                        <a href="javascript: showLoginForm();">登录</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

<script>
    {#判断表单状态#}
    function check(form) {
        if (form.username.value == "") {
            alert("用户名不能为空");
            form.username.focus();
            return false;
        }
        if (form.phone.value == "") {
            alert("手机号不能为空");
            form.phone.focus();
            return false;
        }
        var _phone = $('#phone').val();
        if(!(/^1[3|4|5|8][0-9]\d{8}$/.test(_phone))){
        alert("手机号有误");
        return false;
        }
        if (form.phone.value)

        if (form.password.value == "") {
            alert("密码不能为空");
            form.password.focus();
            return false;
        }
        if (form.password_confirmation.value == "") {
            alert("确认密码不能为空");
            form.password_confirmation.focus();
            return false;
        }
        if (form.password.value != form.password_confirmation.value) {
            alert("两次密码不一致，请重新输入");
            return false
        }
        if (form.error.value == 1){
            alert('此手机号已被注册')
            return false;
        }
        return true
    }
    



    function login(){
				//得到name输入框对象
				var phone1 = document.getElementById("phone1");
				//判断输入框是否有内容
				if(phone1.value.length==0){
					confirm("手机号不能为空");
					return false;
				}

				var pass = document.getElementById("password1");
				if(pass.value.length==0){
					confirm("密码不能为空");
					return false;
				}
				return true;
			}
</script>

基于Django导航系统/templates/search.html
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no, width=device-width">
    <title>线路搜索</title>
    <link rel="stylesheet" href="/static/css/demo-center.css"/>
    <style>
        html,
        body,
        #container {
            width: 100%;
            height: 100%;
        }

        .info1 {
            padding: .75rem 1.25rem;
            margin-bottom: 1rem;
            border-radius: .25rem;
            position: fixed;
            top: 1.8rem;
            background-color: white;
            width: auto;
            min-width: 22rem;
            border-width: 0;
            right: 1rem;
            box-shadow: 0 2px 6px 0 rgba(114, 124, 245, .5);
            height: 120px;
            text-align: center;
        }

        .btn {
            min-width: 60px;
            padding: 5px 8px;
            background: #fff;
            color: #4daff9;
            border: 1px solid #4daff9;
            float: left;
        }

        .btn:hover {
            color: #fff;
            background: #0a90f5;
        }

        .btn:focus {
            color: #fff;
            background: #0a90f5;
            outline: none;
        }
    </style>
</head>
<body>
<div id="container"></div>
<div class="info1">
    {% if token %}
        <form method="post" action="{% url 'design:drawing' %}" onsubmit="return check(this)">
            {% csrf_token %}
            <div class="input-item">
                <div class="input-item-prepend">
                    <span class="input-item-text" style="width:8rem;">请输入起点</span>
                </div>
                <input id='start' name="start" type="text">
            </div>
            <div class="input-item">
                <div class="input-item-prepend">
                    <span class="input-item-text" style="width:8rem;">请输入终点</span>
                </div>
                <input id='end' name="end" type="text">
            </div>
            <input class="btn" type="submit" value="查询并收藏">
        </form>
    {% else %}
        <form method="post" action="{% url 'design:drawing' %}" onsubmit="return check(this)">
            {% csrf_token %}
            <div class="input-item">
                <div class="input-item-prepend">
                    <span class="input-item-text" style="width:8rem;">请输入起点</span>
                </div>
                <input id='start' name="start" type="text">
            </div>
            <div class="input-item">
                <div class="input-item-prepend">
                    <span class="input-item-text" style="width:8rem;">请输入终点</span>
                </div>
                <input id='end' name="end" type="text">
            </div>
            <input class="btn" type="submit" value="点击查询">
        </form>
    {% endif %}
    <a href="{% url 'design:index' %}">
        <input class="btn" type="submit" value="返回首页">
    </a>
</div>
<script type="text/javascript"
        src="https://webapi.amap.com/maps?v=1.4.14&key=b88893a5bf189350d47e335b55ad8794&plugin=AMap.Autocomplete"></script>
<script type="text/javascript" src="/static/js/addtoolbar.js"></script>
<script type="text/javascript">
    var map = new AMap.Map("container", {
        resizeEnable: true
    });
    //输入提示
    var auto = new AMap.Autocomplete({
        input: "start"
    });
    var auto = new AMap.Autocomplete({
        input: "end"
    });

    function check(form) {
        if (form.start.value == "") {
            alert("请输入起点");
            form.start.focus();
            return false;
        }
        if (form.end.value == '') {
            alert("请输入终点")
            form.end.focus();
            return false;
        }
        return true
    }
</script>
</body>
</html>